### ISSUE TITLE
Integrating JSON-SIMPLE for parsing JSON

### ISSUE THREAD

**Issue by wenzhao91** [cs2103aug2015-w09-3j/main#19]
Learning about how custom java objects and Arrays/ Arraylist should be converted to and from JSON with the JSON-Simple 

https://code.google.com/p/json-simple/

**Comment by wentjun** [comment]
We are using both json-simple and gson(https://github.com/google/gson). 

I have already added external archives for both json-simple and gson.

Worked on the JSONConverter which converts tasks(ArrayList) to JSON objects.
